name:                haskell-github-api
version:             0.1.1.0
github:              "jbrgfx/haskell-github-api"
license:             MIT
author:              "James B. Ross"
maintainer:          "jbrgfxblogspot@gmail.com"
copyright:           "2019 James B. Ross"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/github22#readme>

dependencies:
- base >= 4.7 && < 5
- base-compat
- github
- text

library:
  source-dirs: src

executables:
  hask-github-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-github-api

tests:
  github22-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-github-api
